version: '3.1'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  migrate:
    entrypoint: goose up
    build:
      context: ./storage/migrate
      dockerfile: Dockerfile
    volumes:
      - ./storage/migrate:/migrate
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: host=postgres user=postgres password=postgres dbname=azartio sslmode=disable
